server:
   port: 8082
   address: 127.0.0.1

spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties: 
            hibernate:
                format-sql: true


wompi:
    public-key: ${PUBLIC_KEY}
    private-key: ${PRIVATE_KEY}
    integrity-secret: ${INTEGRITY_SECRET}
    event-secret: ${EVENT_SECRET}
    base-url: ${BASE_URL}
    redirect-url: ${REDIRECT_URL}
    verificar-url: ${VERIFICAR_URL}